#cloud-config
package_update: true
package_upgrade: true
users:
  - name: root
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCojLcQzF/iNrv/zD2twmEMfEvfLxP5lgKaZCXxjUz6FM+VXWsrOKWX4GYGvKwjnyPjOJEJX1OeOJF8YPk0lNM/c2cOlzDO3tRd0XG2aNiP6F5WTHzS3JTH3VDPhYvEiqmE3lzPthxcHjdkKs19mhhrQ2ChaXuVzhDkFQIeDrFNg8tjGt8GXEolomjKkJJDaYZuXsF+3qxPkgChj6p6dvHDFsCzIc4StVxFqEMRmEvMsMzAfdrpkzEw+tzsZ3M4ZlufiujjHPQDXs801b8I52fNDCtVg0pcfQxLL79lSPKMymP7lm+kBzLYJdly5tTmDc2tShmxXJYQ/FfpfslEIBPdkbnflTJYj5XrgexlYGvIH8cwRay1kGGgxWOfqa3aAWPcKF0JFHJZC1OSiBJ3LvgmNJoEtn6WnEYoi+iME3Njgydt//UFPDUj4pcGxo5Wnf5xTjztWCRB3UOc03OCmWBdzqvLNkTS8/XkoeSp2wQ7/EzIammMcFtk3O7AG3f+wJJKLgCxmPKRdKKyZVmhbyaH7CqQhDFJDz+GtIPCkKvGL/LIxgx17BThItnibLKR6bf1SRyO//KITWWcp5Gw4gMNztuOC/WGOX5EfPFaAiWEVmJGVW4/mi9rxz119pPkOGjBUSLhuXUcSnDF+iTr5aNiGZhsG5MEOXoi2qF1RA/G+w== egorka
    lock_passwd: false
    hashed_passwd: $6$lSMlUYGHL$EwbHQCQl0b4rXnUU.DSTNY/Ov8BxpzK0HNViHf8u/n7IiPuk7/5ttWCom.EIcD5YHSS1EiHVsGQkUkv0qFodk/
runcmd:
- [apt, purge, -y, cloud-init]

# runcmd:
final_message: "The system is finally up, after $UPTIME seconds"
